version: '3.3'
services:
  development:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/config
      - ~/projetos/pd/:/code
    secrets:
      - host_ssh_key
    stdin_open: true
    tty: true
    hostname: 'development'

secrets:
  host_ssh_key:
    file: ~/.ssh/key
