version: '3.0'
services:
  development:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/config
      - ~/projetos/pd/:/code
    stdin_open: true
    tty: true
    hostname: 'development'

